services:
  postgres:
    image: postgres:latest
    container_name: delivery_postgres
    environment:
      POSTGRES_USER: ilyas
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delivery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ilyas -d delivery_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: delivery_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/delivery_db
      - SPRING_DATASOURCE_USERNAME=ilyas
      - SPRING_DATASOURCE_PASSWORD=password
    # Wait for PostgreSQL to be fully ready before starting the app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: